### ISSUE TITLE
Visual Studio build fails

### ISSUE THREAD

**Issue by desesc** [Zorkator/libfde#14]
Opening VS/libfde.vfproj with Visual Studio 2017 and Intel Fortran 17.0.5 fails due to missing modules.
Build log:
```
------ Build started: Project: libfde, Configuration: Release x64 ------
type preprocessing containertypes
type preprocessing item
type preprocessing hashmap_impl
type preprocessing string
type preprocessing ref
type preprocessing hashmap
type preprocessing list
type preprocessing basetypes
Compiling with Intel(R) Visual Fortran Compiler 17.0.5.267 [Intel(R) 64]...
item.f90
D:\Coding\Github\libfde\src/item.f90(7): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [FDE_REF]
D:\Coding\Github\libfde\src/item.f90(8): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [FDE_STRING]
...
```

I noticed libfde depends on libfortres while digging around, and compiled that one first. And tried again to no avail.
I thought maybe it used to worked and was broken. Si I tried some of the tags, all with similar issues.

I checked the Readme.rst but found nothing about building with Visual Studio.
I eventually got it build after manually compiling indidual files in the right order.
Is there an established build procedure?

**Comment by Zorkator** [comment]
Hi desec,
thank's for your feedback!
Yes, this is a known problem, because unfortunately there's (as far as I know) no way to specify the build order within the VS-build configuration file (.vfproj) that we provide so far.
As you already found out, the apparently missing files are those that get generated by the python script - and VS does only check the building order when loading a project.
So one (not really clever) workaround is triggering a build that will first generate the .f90-files, let it fail, once they are generatated, and after unloading and reloading the project it should build just fine.
That's why we are switched to cmake. It's configuration is already in the [develop](https://github.com/Zorkator/libfde/tree/develop) branch and very stable - there are only very little missing to make up the new release 2.7.3. 
So I'd recomment installing cmake and generating the VS-build config.

saludos,
Josef

**Comment by Zorkator** [comment]
Please use cmake to generate an appropriate build configuration.
Then build problems caused by compilation order should not occur.
